2013-01-06 10:29:30.613 AssistantForIphone[317:907]  tabBarController:didSelectViewController: 
2013-01-06 10:29:31.438 AssistantForIphone[317:907] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: 2012-12-19-12)'
*** First throw call stack:


    self.configPlist = [self _readConfigPlist];
    
    for(id key in self.configPlist){
        if ([key isEqualToString:CONFIG_KEY_USERNAME]) {
            continue;
        }
        
        NSDictionary* headDict = [[self.configPlist objectForKey:key] objectForKey:CONFIG_KEY_HEADINFO];
        
        if ([[headDict objectForKey:CONFIG_KEY_MCTYPE] isEqualToString:mcType]) {
            
            if (nil == [headDict objectForKey:CONFIG_KEY_CONFIGNAME]) {
                continue;
            }
            
            [basicConfigItems setObject:[headDict objectForKey:CONFIG_KEY_CONFIGNAME] forKey:key];
        }
    }


So guys, I think I may have sussed it.
Try disabling siri, then look for your Bluetooth device to pair.
 
Let me know how you get on, as I don't have my headphones with me right now, but aree keen to know if this works.
 
Thank you Apple for your help (NOT!) - it took some normal guy on this forum to work it out.





2013-01-06 14:35:26.940 testBluetoothLowEnergy[10450:907] [002] <CBConcretePeripheral: 0x1e830720 UUID = <CFUUID 0x1e83b590> 8250D075-0E56-C941-BB23-4E16FFC49345, Name = "DJI Config", IsConnected = NO>
2013-01-06 14:35:27.269 testBluetoothLowEnergy[10450:907] [003] <CBConcretePeripheral: 0x1e830720 UUID = <CFUUID 0x1e83b590> 8250D075-0E56-C941-BB23-4E16FFC49345, Name = "DJI Config", IsConnected = YES>



[9737:907] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x2005ca50> was mutated while being enumerated.'
*** First throw call stack:
(0x38eeb2a3 0x3721597f 0x38eead85 0xb7e9b 0x3a9cd74b 0x38ec05df 0x38ec0291 0x38ebef01 0x38e31ebd 0x38e31d49 0x37c682eb 0x3a4032f9 0xaf337 0xaf2d8)
libc++abi.dylib: terminate called throwing an exception






